### ISSUE TITLE
Need class to disable for specific links

### ISSUE THREAD

**Issue by billerickson** [WebDevStudios/Hash-Link-Scroll-Offset#1]
I'm using links to navigate a jQuery tabbed area ( screenshot: http://cl.ly/image/2X0h35271x3L ). When using this plugin, clicking on a tab moves the browser up so the tabbed area gets further and further.

I added a class of .no-scroll to those links, then made the following modification to the plugin's JS file which fixed it: https://www.diffchecker.com/8fcfj5vt

**Comment by jtsternberg** [comment]
Great idea, thanks @billerickson.
