### ISSUE TITLE
Seems to work but it moves right after

### ISSUE THREAD

**Issue by acolombo11** [WebDevStudios/Hash-Link-Scroll-Offset#11]
http://www.coopilmandorlo.com/

This is the page I'm talking about. The plugin seems to work, clicking the anchor link it moves correctly 90px before the anchor, but right after scrolls automatically down to the anchor.

Could you help me with it?

**Comment by jtsternberg** [comment]
This is because you have another script in your theme or in a plugin, etc that's already performing some scrolling stuff. I'm thinking our plugin is incompatible with your setup unless you have familiarity with jQuery and can determine the conflict.
