### ISSUE TITLE
Add offset modification for presence of WP Admin Bar

### ISSUE THREAD

**Issue by salcode** [WebDevStudios/Hash-Link-Scroll-Offset#4]
The presence or absence of the WP Admin Bar causes a change in the size of the offset necessary.

It seems that ideally this should be handled in the JavaScript, where the presence or absence of the WP Admin Bar is detected and the offset modified.  

The question is what does this offset modification look like.
- Is the option set assumed to be with or without the WP Admin Bar?
- Does it make sense to include two options (one for with and one for without the WP Admin Bar)?

**Comment by jtsternberg** [comment]
Agree, offset should be auto-adjusted if the admin bar is visible. The input should be clear that it is asking for the height when the admin bar is not being displayed. I def. don't like the idea of two options.
